describe('TaskCardModal', () => {
  beforeEach(() => {
    // reset the database!
    cy.request('/cypress_rails_reset_state')

    cy.visit('/')
    cy.contains('Workspaces').click()
    cy.get('.Workspace-menu-item').first().click()
    cy.get('body').first().click()
    cy.get('div.Sidebar-wrapper').should('exist')
    cy.get('div.ListItem-board').first().click()
  })
  context('Shows task card modal with task information', () => {
    it('Display and close task card modal', () => {
      cy.get('.TaskCard-label').parent().last()
        .click()
      cy.get('div.TaskCardModal-sidebar').should('exist')
      cy.get('div.TaskCardModal-main').should('exist')
      cy.get('body').click(0, 0)
      cy.get('div.TaskCardModal-wrapper').should('not.exist')
    })
    // TODO add contains('Author name')
    it('Display task Author', () => {
      cy.contains('Add CI tests')
        .click()
      cy.get('div.TaskCardModal-wrapper').should('exist')
      cy.get('div.TaskCardModal-sidebar').should('exist')
      cy.get('div.TaskCardModal-sidebar-card-box').should('exist')
    })
    it('Display task Priority', () => {
      cy.contains('Add CI tests')
        .click()
      cy.get('div.TaskCardModal-wrapper').should('exist')
      cy.get('div.TaskCardModal-sidebar').should('exist')
      cy.get('div.TaskCardModal-sidebar-card-box-taskPriority').should('exist')
    })
    it('Display task Points', () => {
      cy.contains('Add CI tests')
        .click()
      cy.get('div.TaskCardModal-wrapper').should('exist')
      cy.get('div.TaskCardModal-sidebar').should('exist')
      cy.get('div.TaskCardModal-sidebar-card-box-points').should('exist')
    })
    it('Display task Tags', () => {
      cy.contains('Add CI tests')
        .click()
      cy.get('div.TaskCardModal-wrapper').should('exist')
      cy.get('div.TaskCardModal-sidebar').should('exist')
      cy.get('.TaskCardModal-sidebar-card-box-tags').should('exist')
    })
    // TODO add contains('user name')
    it('Display task Assigned', () => {
      cy.contains('Add CI tests')
        .click()
      cy.get('div.TaskCardModal-wrapper').should('exist')
      cy.get('div.TaskCardModal-sidebar').should('exist')
      cy.get('div.TaskCardModal-sidebar-card-box').should('exist')
    })
    it('Display task Label', () => {
      cy.contains('Add CI tests')
        .click()
      cy.get('div.TaskCardModal-wrapper').should('exist')
      cy.get('div.TaskCardModal-main').should('exist').contains('Add CI tests')
    })
    it('Display task Description', () => {
      cy.contains('Add CI tests')
        .click()
      cy.get('div.TaskCardModal-wrapper').should('exist')
      cy.get('div.TaskCardModal-main-description-markdown-text').should('exist').contains('Enim iste qui')
    })
    it('Display task Comment', () => {
      cy.contains('Add CI tests')
        .click()
      cy.get('div.TaskCardModal-wrapper').should('exist')
      cy.get('div.TaskComments-wrapper').should('exist').contains('Facilis ullam commodi')
    })
  })
})
